project:
  type: book

book:
  title: "Aprendizaje Reforzado"
  author: "David Peña Peralta"
  date: "2/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



