project:
  type: book

book:
  title: "CursoVAR"
  author: "David Peña Peralta"
  date: "14/10/2024"
  chapters:
    - index.qmd
    - InventoryModel.qmd
    - InversionModel.qmd
    - SoccerModel.qmd
    - SIRVModel.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



